[package]
name = "maroon-migrator"
version = "0.1.0"
edition = "2024"

[dependencies]
chrono = "0.4.40"
env_logger = "0.11.6"
etcd-client = "0.14.1"
log = "0.4.26"
rand = "0.8.5"
tokio = { version="1.43.0", features = ["full"] }
