[package]
name = "maroon-migrator"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.98"
chrono = "0.4.40"
env_logger = "0.11.6"
etcd-client = "0.14.1"
libp2p = { version = "0.55.0", default-features = false, features = [
    "tcp",
    "tokio",
    "noise",
    "yamux",
    "gossipsub",
    "ping",
    "macros",
    "plaintext"
] }
log = "0.4.26"
rand = "0.8.5"
tokio = { version = "1.43.0", features = ["full"] }
futures = "0.3"

