[package]
name = "common"
version = "0.1.0"
edition = "2024"

[dependencies]
serde = { workspace = true }
libp2p = { workspace = true }
libp2p-request-response = { workspace = true }
derive_more = { version = "2.0.1", features = ["add", "add_assign", "display"] }